[package]
name = "keito-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
dotenvy = "0.15.7"
gfarch = "0.2.3"
poise = "0.6.1"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
zip = "2.6.1"

